const administradorPermisos = [
  // Autenticación y gestión de usuarios
  "auth.iniciarsesion",
  "auth.usuarios.crear",
  "auth.usuarios.editar",
  "auth.usuarios.ver",
  "auth.usuarios.eliminar",
  "auth.usuario.choferes",
  "auth.usuario.vendedores",
  "auth.permisos.crear",
  "auth.permisos.editar",
  "auth.permisos.ver",
  "auth.permisos.eliminar",
  "auth.roles.crear",
  "auth.roles.editar",
  "auth.roles.ver",
  "auth.roles.eliminar",
  "auth.empresa.crear",
  "auth.empresa.editar",
  "auth.empresa.ver",
  "auth.empresa.eliminar",
  "auth.sucursal.crear",
  "auth.sucursal.editar",
  "auth.sucursal.ver",
  "auth.sucursal.eliminar",
  "auth.auditLogs.ver",
  "auth.securitysettings.ver",
  "auth.securitysettings.editar",
  "auth.perfil.ver",


  // Inventario general
  "inventario.producto.crear",
  "inventario.producto.editar",
  "inventario.producto.ver",
  "inventario.producto.eliminar",
  "inventario.productoretornable.crear",
  "inventario.productoretornable.editar",
  "inventario.productoretornable.ver",
  "inventario.productoretornable.eliminar",
  "inventario.inventario.crear",
  "inventario.inventario.editar",
  "inventario.inventario.ver",
  "inventario.inventario.eliminar",
  "inventario.inventariologs.ver",
  "inventario.insumo.crear",
  "inventario.insumo.editar",
  "inventario.insumo.ver",
  "inventario.insumo.eliminar",
  "inventario.tipoinsumo.crear",
  "inventario.tipoinsumo.editar",
  "inventario.tipoinsumo.ver",
  "inventario.tipoinsumo.eliminar",
  "inventario.estadoproducto.ver",
  "inventario.estadoproductoretornable.ver",
  "inventario.categoriaproducto.crear",
  "inventario.categoriaproducto.editar",
  "inventario.categoriaproducto.ver",
  "inventario.categoriaproducto.eliminar",

  // Entregas y logística
  "entregas.agendacarga.crear",
  "entregas.agendacarga.editar",
  "entregas.agendacarga.ver",
  "entregas.agendacarga.eliminar",
  "entregas.agendaviaje.ver",
  "entregas.camion.crear",
  "entregas.camion.editar",
  "entregas.camion.ver",
  "entregas.camion.eliminar",
  "entregas.entrega.ver",
  "entregas.entrega.editar",
  "entregas.inventariocamion.ver",
  "entregas.inventariocamionlogs.ver",
  "entregas.historialventaschofer.ver",
  "entregas.ventaschofer.ver",
  "entregas.agendacarga.confirmar",

  // Ventas
  "ventas.venta.crear",
  "ventas.venta.editar",
  "ventas.venta.ver",
  "ventas.venta.eliminar",
  "ventas.pedido.crear",
  "ventas.pedido.editar",
  "ventas.pedido.ver",
  "ventas.pedido.eliminar",
  "ventas.cotizacion.crear",
  "ventas.cotizacion.editar",
  "ventas.cotizacion.ver",
  "ventas.cotizacion.eliminar",
  "ventas.documento.crear",
  "ventas.documento.editar",
  "ventas.documento.ver",
  "ventas.pago.crear",
  "ventas.pago.editar",
  "ventas.pago.ver",
  "ventas.movimientocaja.crear",
  "ventas.movimientocaja.ver",
  "ventas.historialcaja.ver",
  "ventas.metodopago.ver",
  "ventas.estadopago.ver",
  "ventas.estadoventa.ver",

  "vistas.dashboard.ver",
  "vistas.admin.ver",
  "vistas.usuarios.ver",
  "vistas.roles.ver",
  "vistas.seguridad.ver",
  "vistas.productos.ver",
  "vistas.productos.gestionar",
  "vistas.insumos.ver",
  "vistas.insumos.gestionar",
  "vistas.categorias.ver",
  "vistas.categorias.gestionar",
  "vistas.tipoinsumos.ver",
  "vistas.tipoinsumos.gestionar",
  "vistas.camiones.ver",
  "vistas.agendaCarga.ver",
  "vistas.puntoventa.ver",
  "vistas.pedidos.ver",
  "vistas.puntopedido.ver",
  "vistas.pagos.ver",
  "vistas.facturas.ver",
  "vistas.clientes.ver",
  "vistas.cajas.ver",
  "vistas.perfil.ver",
  "vistas.analisis.ver",

  // funcionales
  "ventas.pedido.confirmar",

  "ventas.pedido.pago",

  "ventas.pedido.asignar",

  "ventas.pedido.desasignar",
  "ventas.factura.registrar",
  "entregas.ventaschofer.ver",
  "ventas.pedido.asignados",
  "ventas.pedido.historial",
  "ventas.movimiento.ver",
];

export default administradorPermisos;
